use crate::{
    core::{
        device::{ctx::DeviceCtx, interface::DeviceImpl},
        event::{
            channel_events::DeviceToChannel, device_events::DeviceOutput, node_events::DeviceToNode,
        },
        node::protocol_key::NodeProtocolKey,
        util::{
            address::MacAddress,
            duration::Duration,
            packet::{
                Packet, Wrap,
                data::PacketData,
                header::{
                    Header,
                    ethernet::{EthernetHeader, crc32},
                },
            },
        },
    },
    devices::queue::{PacketQueue, PopReceipt},
};

const CRC32_CHECK: u32 = 0x2144_DF1C;

pub struct EthernetDevice {
    packet_queue: Box<dyn PacketQueue>,
    /// Receipt for the frame currently on the wire; `Some` means a
    /// transmission is outstanding and its queue slot is still reserved.
    in_flight: Option<PopReceipt>,
}

impl DeviceImpl for EthernetDevice {
    fn on_packet_from_node(
        &mut self,
        ctx: &DeviceCtx,
        packet: Packet,
        protocol: NodeProtocolKey,
        dest_mac: MacAddress,
    ) -> Vec<(Duration, DeviceOutput)> {
        let source_mac = ctx.mac_addr;
        let header = EthernetHeader::new(source_mac, dest_mac, protocol.into());
        let frame = packet.wrap(header, ctx.sim_ctx.id_generator.new_packet_id());
        self.packet_queue.push(frame);
        if self.in_flight.is_some() {
            return vec![];
        }
        self.send_next()
    }

    fn on_packet_from_channel(
        &mut self,
        ctx: &DeviceCtx,
        packet: Packet,
    ) -> Vec<(Duration, DeviceOutput)> {
        if !(crc32(&packet) == CRC32_CHECK) {
            return vec![];
        }
        let (header, payload, _) = packet.unwrap();
        let Header::Ethernet(header) = header else {
            return vec![];
        };
        if header.destination_mac() != ctx.mac_addr {
            return vec![];
        }
        let PacketData::Packet(payload) = payload else {
            return vec![];
        };
        vec![(
            Duration::ZERO,
            DeviceOutput::ToNode(DeviceToNode::Data(*payload)),
        )]
    }

    fn on_channel_free(&mut self, _ctx: &DeviceCtx) -> Vec<(Duration, DeviceOutput)> {
        if let Some(receipt) = self.in_flight.take() {
            self.packet_queue.commit(receipt);
        }
        self.send_next()
    }

    fn on_channel_busy(
        &mut self,
        _ctx: &DeviceCtx,
        returned_packet: Packet,
    ) -> Vec<(Duration, DeviceOutput)> {
        let receipt = self
            .in_flight
            .take()
            .expect("channel returned a packet but no transmission is outstanding");
        self.packet_queue.requeue(receipt, returned_packet);
        vec![]
    }
}

impl EthernetDevice {
    /// Pops the next frame and puts it on the wire, holding its receipt until
    /// the channel reports the transmission's fate.
    fn send_next(&mut self) -> Vec<(Duration, DeviceOutput)> {
        let Ok((frame, receipt)) = self.packet_queue.pop() else {
            return vec![];
        };
        self.in_flight = Some(receipt);
        vec![(
            Duration::ZERO,
            DeviceOutput::ToChannel(DeviceToChannel::Send(frame)),
        )]
    }
}

#[cfg(test)]
mod tests {
    use super::CRC32_CHECK;
    use crate::core::util::{
        address::MacAddress,
        id::IdGenerator,
        packet::{
            Packet, Wrap,
            header::ethernet::{EtherType, EthernetHeader, crc32},
        },
        size::SizeOf,
    };

    /// Raw payload wrapped in an ethernet frame, FCS generated by `wrap`.
    fn build_frame() -> Packet {
        let ids = IdGenerator::new();
        let payload = Packet::from_raw_data(b"crc test payload".to_vec(), ids.new_packet_id());
        let header = EthernetHeader::new(
            MacAddress::new([0x02, 0x00, 0x00, 0x00, 0x00, 0x01]),
            MacAddress::new([0x02, 0x00, 0x00, 0x00, 0x00, 0x02]),
            EtherType::Ipv4,
        );
        payload.wrap(header, ids.new_packet_id())
    }

    #[test]
    fn wrap_generates_fcs_that_verifies() {
        // crc over header + payload + appended FCS yields the CRC-32 residue
        assert_eq!(crc32(&build_frame()), CRC32_CHECK);
    }

    #[test]
    fn corrupted_payload_fails_verification() {
        let mut frame = build_frame();
        frame[14] ^= 0x01; // first payload byte, just past the 14-byte header
        assert_ne!(crc32(&frame), CRC32_CHECK);
    }

    #[test]
    fn corrupted_header_fails_verification() {
        let mut frame = build_frame();
        frame[0] ^= 0x01; // first byte of the destination mac
        assert_ne!(crc32(&frame), CRC32_CHECK);
    }

    #[test]
    fn corrupted_fcs_fails_verification() {
        let mut frame = build_frame();
        let last = frame.size().as_bytes() as usize - 1;
        frame[last] ^= 0x01; // last trailer byte
        assert_ne!(crc32(&frame), CRC32_CHECK);
    }
}
